spring.application.name=dsainmotion
server.port=8082

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/dsainmotion
spring.datasource.username=root
spring.datasource.password=janss13@

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jaahnaavvi13@gmail.com
spring.mail.password=ehuoogqokhbeiapd

spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
